// Regenerates the C core's epoch states and validation references from
// NASA JPL Horizons. Run manually (network required):
//   node core/tools/fetch-horizons.ts
// Normal builds and tests use the committed generated files and stay offline.
import { writeFileSync } from 'node:fs';

// Catalog order must match SolarBodyId in core/include/solar_system.h.
// Planets whose moons are not simulated use the system barycentre (4, 6, 7, 8)
// together with a system GM; Earth and Jupiter use the planet centre because
// their satellites are separate bodies.
const bodies: Array<[key: string, command: string]> = [
  ['sun', '10'], ['mercury', '199'], ['venus', '299'], ['earth', '399'], ['mars', '4'],
  ['jupiter', '599'], ['saturn', '6'], ['uranus', '7'], ['neptune', '8'],
  ['moon', '301'], ['io', '501'], ['europa', '502'], ['ganymede', '503'], ['callisto', '504'],
];
const EPOCH = '2026-09-21 00:00';
const STOP = '2026-10-21 00:00';
const REFERENCE_DAYS = [1, 30];

type State = number[]; // x, y, z (m), vx, vy, vz (m/s)
const epochStates: State[] = [];
const referenceStates: State[][] = REFERENCE_DAYS.map(() => []);
let apiVersion = '';

for (const [key, command] of bodies) {
  const query = new URLSearchParams({
    format: 'json', COMMAND: `'${command}'`, OBJ_DATA: 'NO', MAKE_EPHEM: 'YES',
    EPHEM_TYPE: 'VECTORS', CENTER: "'500@0'", REF_PLANE: 'ECLIPTIC', REF_SYSTEM: 'ICRF',
    TIME_TYPE: 'TDB', START_TIME: `'${EPOCH}'`, STOP_TIME: `'${STOP}'`, STEP_SIZE: "'1 d'",
    OUT_UNITS: 'KM-S', VEC_TABLE: '2', VEC_CORR: 'NONE', CSV_FORMAT: 'YES',
  });
  // Horizons asks for one request at a time; keep this loop sequential.
  const response = await fetch(`https://ssd.jpl.nasa.gov/api/horizons.api?${query}`, { signal: AbortSignal.timeout(30000) });
  if (!response.ok) throw new Error(`Horizons HTTP ${response.status} for ${key}`);
  const result = await response.json() as { result?: string; error?: string; signature?: { version: string } };
  if (result.error || !result.result?.includes('$$SOE')) throw new Error(result.error ?? `Missing vectors for ${key}`);
  apiVersion = result.signature?.version ?? apiVersion;
  const rows = result.result.split('$$SOE')[1].split('$$EOE')[0].trim().split('\n')
    .map(line => line.split(',').slice(2, 8).map(value => Number(value) * 1000));
  if (rows.length !== 31 || rows.some(row => row.length !== 6 || !row.every(Number.isFinite))) {
    throw new Error(`Unexpected Horizons table for ${key}`);
  }
  epochStates.push(rows[0]);
  REFERENCE_DAYS.forEach((day, index) => referenceStates[index].push(rows[day]));
  console.log(`${key}: ok`);
}

const retrieved = new Date().toISOString().slice(0, 10);
const header = [
  '/* Generated by core/tools/fetch-horizons.ts. Do not edit by hand. */',
  `/* Source: NASA JPL Horizons API ${apiVersion}, retrieved ${retrieved}. */`,
  '/* Solar-system barycentre, J2000 ecliptic (ICRF), geometric, TDB. */',
  '/* Rows follow SolarBodyId; columns x y z (m), vx vy vz (m/s). */',
].join('\n');
const format = (state: State) => `{ ${state.map(value => value.toExponential(15)).join(', ')} }`;
const table = (states: State[], indent: string) =>
  states.map((state, index) => `${indent}/* ${bodies[index][0]} */ ${format(state)}`).join(',\n');

writeFileSync(new URL('../src/solar_system_epoch.inc', import.meta.url), `${header}
/* Epoch: ${EPOCH} TDB. */
static const double EPOCH_STATES[SOLAR_CATALOG_COUNT][6] = {
${table(epochStates, '    ')}
};
`);

writeFileSync(new URL('../tests/horizons_reference.inc', import.meta.url), `${header}
/* Reference states ${REFERENCE_DAYS.join(' and ')} TDB days after the epoch. */
static const double HORIZONS_REFERENCE_DAYS[${REFERENCE_DAYS.length}] = { ${REFERENCE_DAYS.map(day => day.toFixed(1)).join(', ')} };
static const double HORIZONS_REFERENCE_STATES[${REFERENCE_DAYS.length}][SOLAR_CATALOG_COUNT][6] = {
${referenceStates.map(states => `    {\n${table(states, '        ')}\n    }`).join(',\n')}
};
`);
console.log('wrote core/src/solar_system_epoch.inc and core/tests/horizons_reference.inc');
